version: "3"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/app
    ports:
      - "8000:80"
    networks:
      - app
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    user: "1000:1000"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app


networks:
  app:

volumes:
  redis_data: